### ISSUE TITLE
Multiple deaths lead to several unbreakable gravestones

### ISSUE THREAD

**Issue by jefferyrlc** [BenCodez/GraveStonesPlus#1]
Had players on my server die repeatedly in places leaving armor stand shaped gravestones that do not break or despawn
![Screenshot_20211129_232918](https://user-images.githubusercontent.com/18264856/143985822-8bdb4bed-ba7a-48cf-8249-21e838021567.png)
.

**Comment by BenCodez** [comment]
With the latest version do they show up in /gravestonesplus allgraves?

**Comment by AbramsX** [comment]
No they do not (I am an Op on the server)
I've also attempted the various commands (reload, KillGravesRadius and CheckValidGraves) to no avail

Jeff has also attempted to reinstall the plugin manually with no success.

**Comment by BenCodez** [comment]
From the plugin page:

    Removing Plugin/Graves:
    In the event a hologram/armor stand needs to be removed use this command: /gravestonesplus KillGravesRadius. In the 
    event that fails use this command: /minecraft:kill @e[type=armor_stand,r=10]

**Comment by AbramsX** [comment]
That also did not work

**Comment by AbramsX** [comment]
Stood next to & on top of. I also manually put in the commands and made sure to double & triple check syntax and options I was using, not just copy & pasting

**Comment by BenCodez** [comment]
What is the response after typing the command?

**Comment by AbramsX** [comment]
No entity was found

However I just did /minecraft:kill @e[type=armor_stand] no r=10 (it didn't recognize the command) and now that seems to have finally worked in removing the hologram armor stands
