### ISSUE TITLE
Nasty Case: Waterfall and Gravestones

### ISSUE THREAD

**Issue by Hershbja** [BenCodez/GraveStonesPlus#2]
I found a nasty case where when one of my players "out ran" the water fall and died from falling damage. Then the waterfall "washed" the grave's head away. Making the grave invalid and the player losing their items.

Washing the grave away: The head pops off from the flowing water. Invalidating the grave.

**Comment by BenCodez** [comment]
https://bencodez.com/job/GraveStonesPlus/ this better?

**Comment by Hershbja** [comment]
> https://bencodez.com/job/GraveStonesPlus/ this better?

Okay so now that the head pops off it removes the grave, good for removing the invalid grave. REALLY sucks for the player (Lose everything). 

Is there any way to make it so the head doesn't pop off to invalidate it? It doesn't do this when there is "Stagnant" waterfall (Like when they drown going up a water fall that has already been there.) If not possible then that's okay, i'll just warn them to not outrace an "actively flowing" waterfall.

PS: 
This plugin is really awesome and really useful (We have a few players that can't seem to stay alive) and you're quick with bug issues. I like that, please keep up the good work.

**Comment by BenCodez** [comment]
Does it work with the build I linked above?

**Comment by Hershbja** [comment]
> Does it work with the build I linked above?

As for the result i would like (the grave stays valid so the player can retrieve their inventory), no it doesn't work. I'll get some screenshots and share them

**Comment by Hershbja** [comment]
![2021-12-16_14 26 10](https://user-images.githubusercontent.com/62969340/146458363-e71a696a-6af6-44d6-8b55-3b749c8b4afc.png)
![2021-12-16_14 26 12](https://user-images.githubusercontent.com/62969340/146458372-82fa16d4-2644-42f3-b1a7-7963b6b37560.png)
![2021-12-16_14 26 39](https://user-images.githubusercontent.com/62969340/146458381-59f3fb4b-128e-4ec8-ba00-050bd6a2c9b3.png)
![2021-12-16_14 26 56](https://user-images.githubusercontent.com/62969340/146458384-fa9ea845-7157-4c7f-b629-ee0fa96515d1.png)

**Comment by Hershbja** [comment]
I just discovered that heads (place on the ground) when hit with flowing water, will pop off. So possibly have another option the user can break to get their items?

**Comment by Hershbja** [comment]
Player tested the latest build you made. Retrieving items do not delete the old grave's armor stands so i am forced to kill all armorstands.

**Comment by BenCodez** [comment]
What about now? https://bencodez.com/job/GraveStonesPlus/

I tested it myself, seems to work, but constantly fights water, might have to change that

**Comment by Hershbja** [comment]
> What about now? https://bencodez.com/job/GraveStonesPlus/
> 
> I tested it myself, seems to work, but constantly fights water, might have to change that

It works now. I see what you mean by it fighting water. You could probably have it place a block from where the water is coming from. or potentially move the death stand higher in the stream where the "stagnant" flowing water is so that it doesn't pop the head off.

**Comment by BenCodez** [comment]
I have no way of detected where the water comes from, I do like the idea of moving the grave up, just can't place a grave in the air without other issues

**Comment by Hershbja** [comment]
> I have no way of detected where the water comes from, I do like the idea of moving the grave up, just can't place a grave in the air without other issues

is it possible to detect if the head breaks from water to just replace the head back onto the grave?

**Comment by BenCodez** [comment]
That's exactly what I'm doing right, just causes the water to update, not sure an easy way around that currently

**Comment by BenCodez** [comment]
https://bencodez.com/job/GraveStonesPlus/ I think I fixed issues with the water now.

**Comment by Hershbja** [comment]
Perfect it works!
