### ISSUE TITLE
Head is missing (How do I recover)

### ISSUE THREAD

**Issue by Nikogenia** [BenCodez/GraveStonesPlus#20]
Hello again!

I got another bug. The grave spawned and saved itself to the config file, but the head is missing. Because of that, the grave could not be broken. Here is a screenshot:
![Screenshot 2023-10-18 191438](https://github.com/BenCodez/GraveStonesPlus/assets/140012263/ddbd91e3-674f-401a-a44b-08ef716edf86)

Is there anyway to recover the items? They are in the config file, but it would be difficult to remake them all by hand. If I view the grave with the command and click on a item, the inventory closes instantly.

I am a big fan of your plugin! Thank you for your help!
Nikogenia

btw, I am on the latest version of the spigot page ...

**Comment by BenCodez** [comment]
use /gravestonesplus AllBrokenGraves (Player) and try to recreate it through that, or /gravestonesplus claimgrave might work
