### ISSUE TITLE
Add feature that allows all players to break other graves.

### ISSUE THREAD

**Issue by Darr3n2GG** [BenCodez/GraveStonesPlus#24]
My friends requested me to enable breakothergraves but apparently it is only for server ops.

**Comment by BenCodez** [comment]
you need to enable the config option and give the permission GraveStonesPlus.BreakOtherGraves

**Comment by Darr3n2GG** [comment]
How do I give the permission?

**Comment by BenCodez** [comment]
Use a permissions plugin

**Comment by Darr3n2GG** [comment]
Thanks for the help! Btw wouldn't it be better to have an option to enable breakothergraves for everyone in the server in the config instead of having to add the permission for everyone in the server with another plugin.

**Comment by BenCodez** [comment]
Most servers generally have a permissions plugin, so it doesn't really seem worth it, might add it though.
