### ISSUE TITLE
Grave break problem

### ISSUE THREAD

**Issue by Symmettry** [BenCodez/GraveStonesPlus#26]
If a non-player entity breaks the gravestone, it just returns and doesn't even drop the loot.
Some datapacks have mobs which can do this, which is problematic because now if a player dies to this mob, it will break their grave and the items will all be deleted.
so I think you should just add a check for if it's not a player but a grave just cancel event

**Comment by BenCodez** [comment]
it should already, if you use the display entities feature instead it will be unbreakable by normal means

**Comment by Symmettry** [comment]
One of the players on my smp died to a custom piglin that breaks blocks and his grave got deleted

**Comment by BenCodez** [comment]
Send your config
