### ISSUE TITLE
Information armor stands don't go away.

### ISSUE THREAD

**Issue by Hershbja** [BenCodez/GraveStonesPlus#3]
When a player receives their items, i noticed that the information armor stands will not go away. I have to kill them with /minecraft:kill @e[type=minecraft:armor_stand]
![2021-12-17_22 27 22](https://user-images.githubusercontent.com/62969340/146631812-5317e44a-c1b2-4304-aa1c-9043a1b34ea3.png)
]

**Comment by BenCodez** [comment]
Does this work?
/minecraft:kill @e[type=armor_stand,distance=..4]

This build should also help prevent that https://bencodez.com/job/GraveStonesPlus/

**Comment by Hershbja** [comment]
Information failed to go away after retrieving inventory
![2021-12-18_11 33 13](https://user-images.githubusercontent.com/62969340/146653614-ae6b6ac6-5660-4d22-bf70-1bb05d935c87.png)

**Comment by BenCodez** [comment]
Anything in console?

**Comment by Hershbja** [comment]
![image](https://user-images.githubusercontent.com/62969340/146654626-d1e275dd-dad0-4666-8627-a64449071138.png)

**Comment by BenCodez** [comment]
How are you breaking the skull?

**Comment by Hershbja** [comment]
Holding left click, so mining and breaking the skull.

**Comment by BenCodez** [comment]
https://bencodez.com/job/GraveStonesPlus/ any better?

**Comment by Hershbja** [comment]
> https://bencodez.com/job/GraveStonesPlus/ any better?

I'll have to get back to you later today when i get back home. I appreciate you doing these bug fixes though!

**Comment by Hershbja** [comment]
armor stand and information goes away!
