### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by misofreshh** [BenCodez/GraveStonesPlus#32]
Upon breaking grave in 1.20.4, it duplicates everything on the body, usually 2x or even 3x of everything you had when you died.

**Comment by BenCodez** [comment]
Does this change anything? https://bencodez.com/job/GraveStonesPlus/

**Comment by misofreshh** [comment]
Still happens, it says "You broke your grave!" twice then says "Some items didn't return to the correct slot. It always re equips my armor and tries putting things back to their slots, but it also tries putting the armor in my inventory too, which seems to try just giving me all my stuff again.

**Comment by BenCodez** [comment]
send your config.yml

**Comment by misofreshh** [comment]
[Config.zip](https://github.com/BenCodez/GraveStonesPlus/files/15211080/Config.zip)

**Comment by BenCodez** [comment]
Wanna try enabling this? `UseDisplayEntities: false`

**Comment by misofreshh** [comment]
Seems to have fixed it, thanks for the help!
