### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Kingdom-1** [BenCodez/GraveStonesPlus#33]
I was recently playing on a minecraft server until thousands of duped shulkers appeared on the server. One person let me in on the secret, and here it is:

Step 1:
Obtain a player head
a: Put a waterlogged slab next to a grave

Step 2:
Obtain multiple player heads by repeatedly doing the method mentioned above.

Step 3:
- Die
- Break the grave
- Place a head on top of the grave
- Break the head
- Profit

Video of the glitch:
https://github.com/BenCodez/GraveStonesPlus/assets/169857399/9388527b-cf5c-426a-9f47-a4a42e5b2e54

I hope this can help! 😁

**Comment by BenCodez** [comment]
1. Latest version of the plugin?
2. Try enabling use display entities in config.yml
3. Try this build: https://bencodez.com/job/GraveStonesPlus/

**Comment by Carter4242** [comment]
@Kingdom-1 the pr I have out fixes this. You are gonna need to build it yourself right now though, which requires reverting the commits from 4 days ago if you are building locally.

**Comment by BenCodez** [comment]
Version 1.6.6 on spigot contains the fix.
