### ISSUE TITLE
Bug Report: Graves Can Be Claimed In Other Worlds

### ISSUE THREAD

**Issue by JerichoTorrent** [BenCodez/GraveStonesPlus#34]
Players can claim their grave while in another world. For example: if a player dies in the end, they can claim the grave in the overworld with `/gravestonesplus ClaimGrave` but to make matters worse, they can claim the grave from anywhere (not the configured distance you need to be within the grave)
So now players are abusing the bug and have no stakes when they die, because they know they can jump in a nether portal and just claim it instantly. Please fix or tell me what I might be doing wrong. Thanks!

**Comment by BenCodez** [comment]
This fix it? https://bencodez.com/job/GraveStonesPlus/

**Comment by JerichoTorrent** [comment]
Indeed. Amazed at the speed you cranked that out. I tested it just now on my test server, and could no longer reproduce the issue in the overworld, nether or the end. Excellent job and thank you!
